### ISSUE TITLE
Camera can clip into objects

### ISSUE THREAD

**Issue by MPjeremy** [UnityTechnologies/open-project-1#50] opened 2020-10-03 14:50 UTC
**Short description**
The camera can clip into objects.

**Expected behaviour**
The camera should not be able to clip through objects, or make it so that the object fades out nicely.

**To Reproduce**
1. move the character behind a giant object(for example the mountain)
2. position the camera so that the mountain is right in front of it
3. move forward
4. This (wrong behaviour) happens.

**Notes**
![image](https://user-images.githubusercontent.com/25549410/94994515-9ff37f80-05ca-11eb-90b7-63fd50f7e267.png)

**Comment by Hemanth759** [comment] 2020-10-03 14:56
This is the same as https://github.com/UnityTechnologies/open-project-1/issues/32

**Comment by ciro-unity** [comment] 2020-10-04 06:57
(I edited the opening comment for readability, no need to keep the issue template and all its headers in the issue)

**Comment by ciro-unity** [comment] 2020-10-04 07:04
> This is same as #32

Hmm. In some ways, it's true.

However, as you can see from @MPjeremy's screenshot attached, the player here is visible and the issue is that the camera is clipping through the ground probably because of its near plane property being too close.

In this sense, I should have left open #32 and close this one as a duplicate :)
But the thing is: if we fix #24 that will fix #32, because if the camera can't lose the character from sight, then it can't go "underground". Here (#50) the issue is different: the camera can be above ground and still clip.

So I'll keep this open to track the two slightly different behaviours, and we'll fix both.

**Comment by Barigamb738** [comment] 2020-10-04 10:10
I want to do this is anyone already doing it?

**Comment by SundarakrishnanN** [comment] 2020-10-04 10:15
I have fixed #24 in a clone of the project, but how do I implement the changes to the official project?

**Comment by Barigamb738** [comment] 2020-10-04 10:16
> I have fixed #24 in a clone of the project, but how do I implement the changes to the official project?

You have to make a pull request.

**Comment by SundarakrishnanN** [comment] 2020-10-04 10:21
> > I have fixed #24 in a clone of the project, but how do I implement the changes to the official project?
> 
> https://youtu.be/lYAHmthUO1M
> This video explanes it really well.

Hey @Barigamb738 , I followed it but since I am not assigned to do so,when I tried to publish the changes it said that I am not allowed to but I can create a fork of it instead..Please help me..I am very new to GitHub.
Thank you,

**Comment by Barigamb738** [comment] 2020-10-04 13:54
I don't really understand your problem sorry

**Comment by SundarakrishnanN** [comment] 2020-10-06 16:31
> I don't really understand your problem sorry

Itsok! It got resolved !Thanks for your concern!

**Comment by quayhoian** [comment] 2020-10-14 08:28
TNJ4QJyGLLu15Mi33TuSiNP6a1oCzoMrMp

**Comment by MikailY** [comment] 2020-11-23 16:01
Can't we use cinemachine collider extension to prevent this behaviour?

**Comment by MikailY** [comment] 2020-11-23 16:57
> > Can't we use cinemachine collider extension to prevent this behaviour?
> > Hmm, yes, we could. We might use  it to keep the camera  outside of geometry? Do you want to give it a go?
> 
> But I personally I wouldn't use it to avoid obstruction, so I would fix issue #24 with Cinemachine, but rather with a shader (I'll add a task for this soon!).

I am excited to see how its done with shaders. Thank you for the quick answer btw.

**Comment by ciro-unity** [comment] 2020-11-24 08:19
> I am excited to see how its done with shaders.

You don't want to try and implement it yourself? [If you watch this tutorial](https://www.youtube.com/watch?v=szsWx9IQVDI), it's basically the same thing. You can avoid making the dither shader even, just create a flat colour unlit one. We can tweak it later.

**Comment by MikailY** [comment] 2020-11-24 11:58
I watched the tutorial and I wanna try it if it is okay. I already forked the project. Should I create a new branch and start working on it or go to the forums and discuss about it?

**Comment by ciro-unity** [comment] 2020-11-27 12:07
> I watched the tutorial and I wanna try it if it is okay. I already forked the project. Should I create a new branch and start working on it or go to the forums and discuss about it?

It would be nice if you open a new thread for maybe all camera-related things? And link the issue here. So other people can be aware and follow the process.

I also have some thoughts about this... :D

**Comment by Satvik-Verma** [comment] 2020-12-10 06:35
I'd like to work on this issue. If nobody's on it could you assign me please? I'm new to using GitHub so I've studied the basics on how to clone and how to use git.

**Comment by ciro-unity** [comment] 2020-12-12 20:53
Anyone interested in fixing this? I think we can use the Cinemachine Collider now, but we don't need to care about occlusion because we have the silhouette pass for the character.

**Comment by SundarakrishnanN** [comment] 2020-12-13 13:27
> Anyone interested in fixing this? I think we can use the Cinemachine Collider now, but we don't need to care about occlusion because we have the silhouette pass for the character.

Hey, long ago I had fixed the camera occlusion by the cinemachine collider, So I guess that solved this issue also,Is that ok? If required I shall redo that in the updated project version...Please do let me know...

**Comment by ciro-unity** [comment] 2020-12-19 00:08
> Hey, long ago I had fixed the camera occlusion by the cinemachine collider, So I guess that solved this issue also,Is that ok? If required I shall redo that in the updated project version...Please do let me know...

[The PR you made](https://github.com/UnityTechnologies/open-project-1/pull/72) was a long time ago and many things changed since then, sorry for that! The scene doesn't even exist anymore.

In the end I solved the issue myself by using the collider too, but not by forcing the character into the view at all times, but rather only when the camera enters the ground. Which also kind of solves the issue with the clipping.
You can see the solution on the `main` branch, and in this tweet:
https://twitter.com/CiroContns/status/1338600503714992132

As such, I'll close this issue!

**Closed by ciro-unity** 2020-12-19 00:08 UTC
Labels: bug (minor)
