### ISSUE TITLE
PlantCritter y axis rotation (attack direction) resets during attack animation.

### ISSUE THREAD

**Issue by hinesca** [UnityTechnologies/open-project-1#442] opened 2021-06-04 18:51 UTC
![2021-06-04 11_45_13-UOP1_Project - TestingGround - PC, Mac   Linux Standalone - Unity 2020 3 7f1 Per](https://user-images.githubusercontent.com/38190540/120849408-ecf96e00-c52a-11eb-811c-1203fbeb58ea.png)
![2021-06-04 11_46_19-UOP1_Project - TestingGround - PC, Mac   Linux Standalone - Unity 2020 3 7f1 Per](https://user-images.githubusercontent.com/38190540/120849429-f387e580-c52a-11eb-8c40-d484fe97c838.png)

**Sort description**

When the player approaches a PlantCritter, it rotates to face the character during the alert animation. When the character moves within attack range, the direction that the plant critter faces resets to the instantiated position during the attack animation.

**Expected behavior**

The PlantCritter should maintain attack direction during the attack animation.

**To Reproduce**

1. Open the game play scene and press play.
2. Move the character towards a PlantCritter and allow it to attack.
3. Move the character to the opposite side of the PlantCritter and allow it to attack.
4. Notice how the direction the PlantCritter resets during the attack animation.

**Notes**
- See uploaded files

**Comment by hinesca** [comment] 2021-06-04 19:02
This bug can be assigned to me. It seems that this will be an easy issue to fix. I don't quite have the experience with Unity and this project yet to know exactly where the issue lives within the project, but I intent on learning.

**Comment by shuttle127** [comment] 2021-06-05 21:50
Bugs don't get "assigned" per se, they're just noted and people work on them. If this is something you'd like to figure out, fork the main repo, code up the fix, and make a PR. Hopefully it's a simple enough fix, good luck!

**Comment by amel-unity** [comment] 2021-06-07 14:52
Hello!
Thank you @hinesca  for noticing the issue. This is happening because the Face Protagonist action called on the Alert, Fighting and Reloading states on the state machine of the plant critter is the one meant to be used for the NPC and not the Critter.

When I started working on the state machines of the NPCs, I used the FaceProtagonist action we had in the project, which was used for the critters. However when the protagonist starts talking to a townsfolk, we want them to reset to their initial rotation when they finish the conversation. This means if we have 2 townsfolks talking to each other, and the protagonist starts talking to one of them, the townsfolk will face the protagonist and when they finish the conversation, the townsfolk will reset to his initial position so he looks to the other townsfolk he resumes talking to.

Since this is not what we want for the Critter, I have created a new action called NPCFaceProtagonist which stores the initial rotation and reassign it to the NPC when we exit the state. For the critters we will use the initial FaceProtagonist Action which is now renamed to CritterFaceProtagonist, for this action we don't assign the initial rotation on exit since we don't need it.

The issue is happening because I updated the slime critter state machine (For now also used for the rock critter) to use the CritterFaceProtagonist but I didn't update it for the Plant critter.
I just updated the state machine and pushed it to main, you should be able to see it working properly now on the latest version of main.

Thanks!

**Comment by hinesca** [comment] 2021-06-07 18:10
Great! Thanks, Amel.

Before reading your reply I got a pull request ready to solve this a slightly different way, but it looks like what you have done is more general, and I don't have the experience you do so fee free to ignore it.

Rather then change the animation in the alert state to a new CritterFaceProtagonist animation, I added the existing NPCFaceProtagonist action to the Attack State which also accomplishes the desired behavior.

**Comment by amel-unity** [comment] 2021-06-15 13:08
Hi @hinesca , thank you for opening the PR and looking into the issue. The solution you are suggesting would also work but I will keep the one that is currenlty on main just because if we use the same action, it means that we will be storing the rotation and assigning it again on action exit even though we don't really need it and as this will be used on all the critters and on multiple states (and we will proabably have many critters), it's wiser to avoid those lines of code that we don't really need :) 
Again thanks for opening the issue and suggesting solutions for that.

**Closed** 2021-06-28 12:54 UTC
Labels: bug (important)
