### ISSUE TITLE
Wrong State while falling from a platform without jumping

### ISSUE THREAD

**Issue by erizzoalbuquerque** [UnityTechnologies/open-project-1#187] opened 2020-11-13 21:32 UTC
**Short description**
Protagonist's State Machine Current State goes to Sliding State when it's falling from a platform without jumping.

**Expected behavior**
It seems to me that's it's much more intuitive if the character would go to a Falling State (That doesn't exist) or at least the JumpDescending State.

**To Reproduce**
1. Go to a platform above ground
2. Fall from the platform without jumping.
3. Observe the current state variable on the pig's state machine. It's showing "Sliding" while falling.

**Notes**
- This a very minor bug right now. Maybe instead of fixing this, we can wait until the player's logic is more defined.

**Comment by DeivSky** [comment] 2020-11-16 17:05
This can be fixed by adding a transition from `Sliding` to `JumpDescending` if `IsGrounded` is false.

**Comment by ciro-unity** [comment] 2020-11-16 22:09
A cute little bug :)
I'll leave it open in case somebody new to the project wants to fix it. It's a good first contribution, nice to get used to the state machine.

**Comment by mtakac** [comment] 2020-11-18 19:26
Thank you for leaving it open: It was the best first issue ever! :D

I did play around with the state machine so I created a PR that fixes this issue: #199 

The diff is a bit cryptic, but I hope it's okay. Please do let me know if there's some better way to do it.

**Closed** 2020-11-19 01:40 UTC
Labels: bug (minor), good first issue

**Comment by jandd661** [comment] 2020-11-28 21:44
When working on issue #228 I notice this still occurs. The problem is the player can "hang" off the edge to where `IsSliding = true` and `IsGrounded = true` circumventing this fix.

`IsSliding `is only a check of the angle from `lastHit` location on the character's collider and the normal of the geometry that hit it. Because the bottom of the capsule collider is round, you can put yourself in a situation where the `lastHit` angle is greater than 45 and `IsGrounded` is true but have enough surface friction to not be falling off the edge yet. This also happens very briefly if you run off the edge.

It also interferes with the animation triggers.

Adding `IsActuallyMoving `from PR #227 should solve the "hanging" part but I'm not sure what to do about the brief moment it occurs when you run off the edge. Or if it needs to be dealt with at all.
