### ISSUE TITLE
Player gets stuck in mid-air when colliding with an obstacle

### ISSUE THREAD

**Issue by MEGATANK58** [UnityTechnologies/open-project-1#48] opened 2020-10-03 05:10 UTC
**Short description**
Players can do some movement tricks to align themselves so their hands get stuck in Obstacle,not sure if that's because of the way obstacles are made in the project but its not intended to happen

**Expected behaviour**
Player should not be able to float in air and instead fall to ground

**To Reproduce**
1. Click Play
2. Go to the obstacles in top left side of map
3. Align your hands with the wall (or side) as much as you can
4. Click Jump and you can float (until you click jump again or change your position)

**Notes**
I have tried this in master branch and since snappy movement is patched this can be quite hard to replicate but is still possible (according to my findings)
Here are some in-game screenshots:
![Bug1](https://user-images.githubusercontent.com/51410502/94984304-49555980-0568-11eb-8d49-fc8a79fa5035.png)
![Bug2](https://user-images.githubusercontent.com/51410502/94984306-4c504a00-0568-11eb-95e0-79580f5bbcc8.png)
![Bug3](https://user-images.githubusercontent.com/51410502/94984307-4d817700-0568-11eb-97dd-5249216eaa25.png)

**Comment by MPjeremy** [comment] 2020-10-03 06:01
Hi, could you provide more details? I can't seem to reproduce the problem

**Comment by Hemanth759** [comment] 2020-10-03 07:12
Hey I was able to reproduce.
![image](https://user-images.githubusercontent.com/33123731/94985614-c9ce8700-0575-11eb-8dfb-e3ded8cbc7f0.png)

I think the problem is with the character collider.
![image](https://user-images.githubusercontent.com/33123731/94985625-dd79ed80-0575-11eb-9286-248e9e0c1d42.png)

**Comment by Hemanth759** [comment] 2020-10-03 07:19
So I moved the box collider of the building with some offset in x-axis and found that the player collider getting struck with one side of the box collider. (only one side though remaining side of the box collider works fine).
![image](https://user-images.githubusercontent.com/33123731/94985706-7577d700-0576-11eb-9d65-c04ba4d76a34.png)

**Comment by Hemanth759** [comment] 2020-10-03 07:24
I created simple script which detects the collision on character and draws a line in the editor with one unit long. 
Interestingly I found that the character is colliding with the boxcollider in sideways and that is preventing from falling down.
![image](https://user-images.githubusercontent.com/33123731/94985836-6e9d9400-0577-11eb-9691-1eaf8426cb4b.png)

![image](https://user-images.githubusercontent.com/33123731/94985844-87a64500-0577-11eb-8957-b1c9bc0dd9f2.png)

**Comment by LayalHF** [comment] 2020-10-03 08:39
I can add two small spheres for the hands for collision

**Comment by ciro-unity** [comment] 2020-10-03 11:50
Hey, I've updated the title since apparently the issue is not with the hands.

**Comment by MEGATANK58** [comment] 2020-10-03 11:52
Thank you for updating the title it was quite unknown about the source of the issue earlier so i thought it would be good to start

**Comment by Quickz** [comment] 2020-10-03 16:22
Sounds like #8 

Those small buildings are slightly rotated so you're essentially going uphill on a very steep surface.

**Comment by Hemanth759** [comment] 2020-10-03 16:34
> Sounds like #8
> 
> Those small buildings are slightly rotated so you're essentially going uphill on a very steep surface.

That actually makes sense @Quickz 
So that is why the player wasn't able to jump properly from other side of the box collider as the boxcollider is blocking the player.

**Comment by MEGATANK58** [comment] 2020-10-04 02:32
> Sounds like #8
> 
> Those small buildings are slightly rotated so you're essentially going uphill on a very steep surface.

I think your right so we should fix #18 and that will automatically (or should) fix this

**Comment by ciro-unity** [comment] 2020-10-04 17:11
Let's not close bugs that haven't been fixed. Sure, could be a duplicate and have the same root cause, but we don't know.
If you close it:
- We might lose track of it until way later
- Somebody else might open the bug report again if they see it happen.

**Comment by MEGATANK58** [comment] 2020-10-05 05:12
> Let's not close bugs that haven't been fixed. Sure, could be a duplicate and have the same root cause, but we don't know.
> If you close it:
> 
> * We might lose track of it until way later
> * Somebody else might open the bug report again if they see it happen.
Oh Sorry my bad

**Comment by ciro-unity** [comment] 2020-10-25 12:59
Tempted to close this issue as I haven't seen it happen in a very long while (?)

**Comment by MEGATANK58** [comment] 2020-10-26 03:00
I have done some testing this bug isn't happening anymore it was probably a problem with the mesh or character

**Comment by ciro-unity** [comment] 2020-10-26 14:36
It was most probably an issue connected with how the character controller was coded. But since we have introduced a fix for the slopes, I think it was fixed. Let's close it!

**Closed by ciro-unity** 2020-10-26 14:36 UTC
Labels: bug (minor)

**Comment by ciro-unity** [comment] 2020-10-31 18:12
I don't understand the perspective very well: is the player walking on it, and not sliding down?

**Comment by circa94** [comment] 2020-10-31 18:42
Yes exactly. I wanted to jump on the wall and this is where I was landed. I was able then basically to walk in air on this edge

**Comment by ciro-unity** [comment] 2020-10-31 21:41
Ah I see. It's a wall.

Now the thing to do is: find clear reproduction steps. Can you reproduce the issue easily? Or is it like, one in a dozen intentional tries?

**Comment by circa94** [comment] 2020-11-01 14:53
yes i can reproduce it easily on any wall

![image](https://user-images.githubusercontent.com/6034570/97806079-1c28c380-1c5a-11eb-8de5-75049e514eaf.png)

![image](https://user-images.githubusercontent.com/6034570/97806142-6b6ef400-1c5a-11eb-983b-62b2eb47e638.png)

**Comment by ciro-unity** [comment] 2020-11-11 22:33
Sorry, I had never seen this reply! My bad.

I think that's intentional though, it's because of the size of the collider. He's walking on those corners, technically... ?

Let's revisit this bug later if we keep seeing it with the new settings on the character.
