### ISSUE TITLE
Camera of character controller goes through ground

### ISSUE THREAD

**Issue by notwill111** [UnityTechnologies/open-project-1#32] opened 2020-10-02 01:07 UTC
In the Character controller scene, when the character moves around. Its camera can go through the ground and see under the map.

Camera go's through the ground instead of going over it.

1. Go to 'Character Controller Scene'.
2. Play the scene.
3. Walk over to the mountain and climb over it, and walk down it straight.
4. The camera will go through the mountain.

Notes
![Capture](https://user-images.githubusercontent.com/51319649/94877964-68d47f80-049f-11eb-9a21-17e206cb47d5.PNG)

![Capture](https://user-images.githubusercontent.com/51319649/94878386-835b2880-04a0-11eb-8595-2d92968bc5cc.PNG)

**Comment by ElgenTidwell** [comment] 2020-10-02 02:57
I would like to fix this issue

**Comment by MileyHollenberg** [comment] 2020-10-02 12:41
Keep in mind that the project is using Cinemachine, you can simply fix this with one of the Cinemachine features (not exactly sure which one) so there's no need for any code change on this :)

**Comment by ciro-unity** [comment] 2020-10-02 13:31
This issue is a duplicate of #24, so I'm closing it.
Also what Miley suggests is true.

Thanks anyway!

**Closed by ciro-unity** 2020-10-02 13:31 UTC

**Comment by ciro-unity** [comment] 2020-10-04 07:07
@notwill111 see discussion here: https://github.com/UnityTechnologies/open-project-1/issues/50#issuecomment-703213159

Even though I want to keep the issue closed to avoid too many similar ones, it still added something to the conversation ;)
