### ISSUE TITLE
DialogueManager throw null reference exception if OpenDialogueUIEvent is not initialized.

### ISSUE THREAD

**Issue by rainaldisatria** [UnityTechnologies/open-project-1#343] opened 2021-02-01 09:56 UTC
**Short description**
Just a minor bug that'll occur if DialogueLineEvent in DialogueManager is not initialized.

**Expected behaviour**
Should not throw null reference exception even if DialogueLineEvent is not initialized by UIManager.

**To Reproduce**
1. Go to Scene/Examples/
2. Click on Cutscenes scene
3. Press start button.
4. This (null reference error) happens since DialogueLineChannelSO is not initialized by UIManager.

**Comment by ciro-unity** [comment] 2021-02-14 17:06
Closing the issue because it's not happening anymore due to some null checks implemented in the script.

However, please note that the expected behaviour is misleading:
>Should not throw null reference exception even if DialogueLineEvent is not initialized by UIManager.

This is incorrect, the expected behaviour is that
> the DialogueLineEvent should be initialised

If not initialised, then it **should** throw a NullReferenceException - to warn the developer of an error in the setup.

**Closed by ciro-unity** 2021-02-14 17:06 UTC
Labels: bug (minor)
