### ISSUE TITLE
Jumping throw an exception

### ISSUE THREAD

**Issue by rainaldisatria** [UnityTechnologies/open-project-1#216] opened 2020-11-25 08:19 UTC
**Short description**
Can't jump after new scene is loaded.

**Expected behaviour**
Able to jump without throwing an exception.

https://youtu.be/vviXsrRVSEY

**To Reproduce** 
1. Go to MainMenu scene
2. Click on Start button
3. Press SpaceBar (jump button)  
4. This exception "MissingReferenceException: The object of type 'SoundEmitter' has been destroyed but you are still trying to access it."  happens.

**Notes**
- You can try it in another scene (just make sure you load another scene on that scene)

**Comment by Matcheryt** [comment] 2020-11-25 15:50
I reproduced it on my machine, and by asking unity to not destroy the SoundEmitterPool on load, seems to fix the issue. 
I'm new to the project and would like to continue with the fix. I'm not very experienced with Unity, if someone has a better approach on this let me know!

**Comment by ErikBehar** [comment] 2020-11-25 15:59
yes the issue is that the pool gets created in the Active Scene, when the active scene is destroyed, the pool goes with it. 

There is clearly a line already in the code that is commented : 
ComponentPoolSO: ( line 24 )  			//DontDestroyOnLoad(_poolRootObject); 

The problem here is that this is a generic system, so I think some pools we do want to destroy and some pools we don't ... 
One solution might be to pass in a transform where you want your pool to exist at, that way if you want your pool to survive scene loads, you can instantiate it with a root transform in a scene that is not destroyed, otherwise you can pass in null and that should put it in the active scene.

**Comment by rainaldisatria** [comment] 2020-11-25 16:07
A good first issue.
Yeah, since it's generic, we want to have control of both approach (Destroyed after scene loaded, or the opposite).
My proposition is to add boolean property to ComponentPoolSO called Global or something like that. Then in the SoundEmitterPoolSO, we set the Global = true (Not destroyed after scene loading) in the OnEnable() method

**Comment by davejrodriguez** [comment] 2020-11-25 16:13
Hah I actually was just working on this. I'm not super familiar with this issue, but if it's caused by DDOL, it should be fixed once #215 is merged.

**Comment by ErikBehar** [comment] 2020-11-25 17:37
> Hah I actually was just working on this. I'm not super familiar with this issue, but if it's caused by DDOL, it should be fixable once #215 is merged.
> 
> Solution would be to call Pool.SetParent(t) where t is a transform of an object marked DDOL.

so in your solution the parent is always assumed to be the object the script is on ? Do you prefer to surface the transform as a user facing variable instead?

**Comment by davejrodriguez** [comment] 2020-11-25 18:57
> so in your solution the parent is always assumed to be the object the script is on ? Do you prefer to surface the transform as a user facing variable instead ? I see a code path, but not something a user can tweak with out code, I guess can expose that on the using script.

No assumptions. I think it's _easiest_ in a manager architecture to just use the manager's transform, but there is no preference as far as the pool is concerned. As for changing the targeted transform for parenting in the editor, yes, I would expose a field for the script in the inspector and use that instead.

**Comment by ciro-unity** [comment] 2020-11-28 16:43
Should be fixed by the changes that @davejrodriguez did to the Object Pool. I'll verify later and close it, if necessary.
Thanks @rainaldisatria for reporting it!

**Comment by ErikBehar** [comment] 2020-11-28 16:56
ok you added the setParent line yourself @ciro-unity so yes feel free to close this.

**Closed** 2020-12-08 03:06 UTC
Labels: bug (critical)
