### ISSUE TITLE
Unsaved scene changes dont show in play mode,  Editor cold start doesnt work from mainmenu

### ISSUE THREAD

**Issue by TJHeuvel** [UnityTechnologies/open-project-1#380] opened 2021-02-20 19:08 UTC
https://github.com/UnityTechnologies/open-project-1/blob/04a50f215b184a6f90e828cece44cec2318ebe26/UOP1_Project/Assets/Scripts/SceneManagement/EditorColdStartup.cs#L27

I cannot interact with the Main Menu when i open that scene and press play. I'm not sure why, the graphic raycaster simply doesnt hit anything. It also [seems like my scene changes dissapear](https://dl.dropboxusercontent.com/s/7uh95myvt677lz5/9VI0sZ7XXW.mp4) when i press play, and reappear when exiting. This is not so nice for iteration!

Both seem to be caused by this reloading here. I'm not familiar with the system at all, when i remove this stuff breaks even more, but not being able to see my unsaved changes in playmode is i think a big dealbreaker.

**Comment by ciro-unity** [comment] 2021-02-22 20:02
> I cannot interact with the Main Menu when i open that scene and press play.

That is weird and we should fix it.

> It also [seems like my scene changes dissapear](https://dl.dropboxusercontent.com/s/7uh95myvt677lz5/9VI0sZ7XXW.mp4) when i press play, and reappear when exiting. This is not so nice for iteration!

Yeah, that's an unfortunate consequence of reloading the scene when pressing Play. We currently do this to allow the ability to press Play from any Location scene and then be able to move through the game.

This is the scene architecture we use: https://github.com/UnityTechnologies/open-project-1/wiki/Game-architecture-overview#Scenes
When pressing Play from a random Location scene (so only in the editor), we load PersistentManagers and then that scene reloads the current Location you're in. This is done to simulate the normal flow, so that when you move across Locations the current one is correctly unloaded.
That's why your unsaved changes are flushed (and I hope they return after you exit Play mode, right??).

If we find it very annoying, we could also go another way: not reload the scene, but just load the PersistentManagers additively. This would mean you'd always have to pass through the MainMenu if you want to experience moving between scenes.
The alternative to re-enable play-from-any-scene-and-move-across-locations, we would have to hack the scene loading to allow it.

Opinions?

**Comment by TJHeuvel** [comment] 2021-02-23 10:59
I dont feel very qualified to comment about the setup, i just picked up something small to get familiar with Shader Graph. I tried to fix the issue for mainmenu, but quickly felt overwhelmed because i dont know the setup, and i didnt read any documentation. 

Normally in my projects we have a prefab with persistents, that has an EditorOnly tag, overridden in the Initialization scene to not be editor only. It checks as early as possible if there is already one of those prefabs, and if so, destroys itself. I havent had the need for loading scenes via an Event Channel like system.

> and I hope they return after you exit Play mode, right??

They do, but i just found it counterintuitive that they dissapeared.

**Comment by TJHeuvel** [comment] 2021-02-23 12:13
https://github.com/TJHeuvel/open-project-1/commit/7815c86b821de7077ced5168e5a63f6ac43e2372

Hacked my way into it, but i dont think its good enough to do as a pull request. Basically; just load the persistent scene, and SceneLoader tries its best to guess which GameSceneSO's are loaded when it starts.

**Comment by IsaiahKelly** [comment] 2021-03-16 19:45
> > I cannot interact with the Main Menu when i open that scene and press play.
> 
> That is weird and we should fix it.

This appears to be caused by the same issue I discussed [on the forums](https://forum.unity.com/threads/gameplay-ui-unresponsive-in-editor.1069193/). Essentially, the way the EventSystem object is getting loaded is the problem, because I also had this issue and removing the EventSystem object from the MainMenu scene resolved it.

> The alternative to re-enable play-from-any-scene-and-move-across-locations, we would have to hack the scene loading to allow it.

I think you can actually do this easily without "hacking" anything, and I believe it would resolve both issues mentioned here. So I am currently investigating ways to improve the editor "cold start" system. Although improving the entire loading system itself could also fix these issues.

**Comment by TJHeuvel** [comment] 2021-03-17 06:00
https://github.com/TJHeuvel/open-project-1/commit/7815c86b821de7077ced5168e5a63f6ac43e2372

See my attempt, not too difficult. I just dont know the systems enough.

**Comment by ciro-unity** [comment] 2021-04-27 21:18
Thanks @TJHeuvel, I ended up refactoring quite a lot (for other reasons) but the end of the hack looks a bit like yours.
In my case, I ended up creating a new event channel called "NotifyColdStart" (or something like that), which is basically a fake scene load request only used when pressing Play from the editor, doing slightly different operations.

I'll close the issue then!

**Closed by ciro-unity** 2021-04-27 21:18 UTC
Labels: bug (minor)
