### ISSUE TITLE
NullReferenceException when entering dark red block

### ISSUE THREAD

**Issue by normyp** [UnityTechnologies/open-project-1#488] opened 2021-08-16 18:07 UTC
**Short description**
This sometimes occurs:
```
NullReferenceException: Object reference not set to an instance of an object 
LocationExit.OnTriggerEnter (UnityEngine.Collider other) (at Assets/Scripts/SceneManagement/LocationExit.cs:20)
```
**Expected behaviour**
Should not raise an exception.

**To Reproduce**
Walk into the dark red block near the starting point.

**Comment by ciro-unity** [comment] 2021-08-23 07:32
As mentioned in the PR #489, we generally don't want to prevent NullReference Exceptions. They are a great warning that something is missing, and "silencing" them might lead to invisible bugs in the build.

I'll be closing this soon, just leaving it a bit for yours and others' awareness. Thanks anyway!

**Comment by thedeepakchaturvedi** [comment] 2021-08-25 07:34
The NullReferenceException occurs because we haven't specified the Location To Path & Location Storage to any initial value in the inspector panel, although its value is default in the script. So it is not able to load any scene when we enter the trigger. Is this issue closed ?? Can I work on this issue to remove the error that is preventing scene switching.

**Comment by ciro-unity** [comment] 2021-09-05 10:44
As mentioned in PR #489, the PR and the Bug are looking at the wrong issue and the wrong way to fix it. The issue is in the scene (i.e. the referenced SOs), not in the script. In fact, it doesn't mention the scene where it happens.
So don't worry about fixing it, I'm working on all scenes to wrap up the project so that might cause a conflict. I'll review all entrances/exits.
Thanks though!

**Closed by ciro-unity** 2021-09-05 10:44 UTC
Labels: invalid

**Comment by normyp** [comment] 2021-09-06 08:34
Okay, thanks for your feedback. :-)
