### ISSUE TITLE
The character gets stuck between rocks

### ISSUE THREAD

**Issue by Eddrico** [UnityTechnologies/open-project-1#350] opened 2021-02-03 22:33 UTC
Short description
The character gets stuck between rocks, the directional input is recognized but the character does not move, the character can get out of the place after several tries, This is reproducible with keyboard and Joysticks, but keyboards get stuck longer than joysticks.

Expected behavior
The Character should be able to move.

To Reproduce

    1.- Open a scene with the TestingGround. Press play.
    2.- Jump over the rocks and place the character between them.
    3.- observe that you can not move, you can jump, but can not move in the air either.

Notes

    Here's a video of the issue, you can see the inputs while i tried to get out of the place:
[https://www.youtube.com/watch?v=rdt4VixZmJI&feature=emb_logo](url)

**Comment by phx1999** [comment] 2021-02-24 02:56
Though directional input is useless, you can easily jump out the the stuck. 
Do you mean that you want use WSAD to leave the stuck place? (It seems unreasonable)
Or you want to see the movement ainimation?
Or change the rock architecture so that the character can leave the stuck?

**Comment by JenniTheDev** [comment] 2021-03-19 05:16
I opened up the TestingGround scene and reproduced the bug that the PigChef gets stuck in the same place. I then went to try and reproduce the same bug in other scenes and places. 

Looking at the State Machine Script, whenever the Pig Chef is stuck, the Current State is Sliding. In that state, the only thing it can do is transition to JumpAscending if it's not actually moving. I think this might be causing the bug.  

[Here is a video showing PigChef getting stuck in  a few different places, along with the inspector showing the state changes](https://youtu.be/3tqUvufPbPM)

**Comment by JoaoSant0s** [comment] 2021-03-28 15:59
I'm studing the SlideActionSO.cs and I think that we can use a similar aprouch that was apploued in AerialMovementActionSO.cs

With that, we can aplly a Slide_Resistance to control the movement velocity of the protagonit in this situation.

Trying to figurirout a mathematical alternative to use same logic of the others actions

**Comment by JoaoSant0s** [comment] 2021-03-28 22:27
I tried other aprouch for this problems. I made a comment in the PR description

**Comment by amel-unity** [comment] 2021-04-19 13:18
Hey everyone,
I think it is intended to not be able to leave by simply walking. You just need to jump. So I am not sure if we can still condiser this an issue since we are not stuck but we just need to jump to get out of the rocks. Any thoughts on this or shall we close the issue? 
Thanks :)

**Comment by JenniTheDev** [comment] 2021-04-19 18:29
I think that it can be closed. Maybe a new bug should be made for the player being able to use this to jump up rocks into places where they really shouldn't be?

**Comment by amel-unity** [comment] 2021-04-20 13:28
I will close this issue then, just to avoid that anyone spends time fixing it even though it is not really an issue. Yes @jenniferd-unity, please feel free to open another issue if you notice one, I saw in your video what you are referring to and I was able to reproduce it on the beach scene but I think that issue is coming from the colliders so once we start putting together the final environment we should make sure to tweak the colliders to avoid seeing the character ''jumping in the void''. Thanks :)

**Closed by amel-unity** 2021-04-20 13:28 UTC
Labels: ?, bug (important)
